name: PacketAnalyzer
main: amata1219.packet.analyzer.Main
version: 1.0.0
author: '@amata1219'

commands:
  analyze:
    description: Toggle packet analysis
    usage: /<command>
    permission: packet.analyzer.analyze
    permission-message: You do not have <permission>